// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package resource_policy

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.PolicyDocument, b.ko.Spec.PolicyDocument) {
		delta.Add("Spec.PolicyDocument", a.ko.Spec.PolicyDocument, b.ko.Spec.PolicyDocument)
	} else if a.ko.Spec.PolicyDocument != nil && b.ko.Spec.PolicyDocument != nil {
		if equal, err := ackcompare.IAMPolicyDocumentEqual(*a.ko.Spec.PolicyDocument, *b.ko.Spec.PolicyDocument); err != nil || !equal {
			delta.Add("Spec.PolicyDocument", a.ko.Spec.PolicyDocument, b.ko.Spec.PolicyDocument)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PolicyName, b.ko.Spec.PolicyName) {
		delta.Add("Spec.PolicyName", a.ko.Spec.PolicyName, b.ko.Spec.PolicyName)
	} else if a.ko.Spec.PolicyName != nil && b.ko.Spec.PolicyName != nil {
		if *a.ko.Spec.PolicyName != *b.ko.Spec.PolicyName {
			delta.Add("Spec.PolicyName", a.ko.Spec.PolicyName, b.ko.Spec.PolicyName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ResourceARN, b.ko.Spec.ResourceARN) {
		delta.Add("Spec.ResourceARN", a.ko.Spec.ResourceARN, b.ko.Spec.ResourceARN)
	} else if a.ko.Spec.ResourceARN != nil && b.ko.Spec.ResourceARN != nil {
		if *a.ko.Spec.ResourceARN != *b.ko.Spec.ResourceARN {
			delta.Add("Spec.ResourceARN", a.ko.Spec.ResourceARN, b.ko.Spec.ResourceARN)
		}
	}

	return delta
}
