// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package resource_policy

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/cloudwatchlogs-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.ResourcePolicy{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	// A ResourceArn identifies a resource-scoped policy, which must be queried
	// with the RESOURCE policy scope. DescribeResourcePolicies defaults to the
	// ACCOUNT scope and rejects any request that pairs a ResourceArn with it.
	if r.ko.Spec.ResourceARN != nil {
		input.PolicyScope = svcsdktypes.PolicyScopeResource
	}

	var resp *svcsdk.DescribeResourcePoliciesOutput
	resp, err = rm.sdkapi.DescribeResourcePolicies(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeResourcePolicies", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.ResourcePolicies {
		if elem.LastUpdatedTime != nil {
			ko.Status.LastUpdatedTime = elem.LastUpdatedTime
		} else {
			ko.Status.LastUpdatedTime = nil
		}
		if elem.PolicyDocument != nil {
			ko.Spec.PolicyDocument = elem.PolicyDocument
		} else {
			ko.Spec.PolicyDocument = nil
		}
		if elem.PolicyName != nil {
			if ko.Spec.PolicyName != nil {
				if *elem.PolicyName != *ko.Spec.PolicyName {
					continue
				}
			}
			ko.Spec.PolicyName = elem.PolicyName
		} else {
			ko.Spec.PolicyName = nil
		}
		if elem.PolicyScope != "" {
			ko.Status.PolicyScope = aws.String(string(elem.PolicyScope))
		} else {
			ko.Status.PolicyScope = nil
		}
		if elem.ResourceArn != nil {
			ko.Spec.ResourceARN = elem.ResourceArn
		} else {
			ko.Spec.ResourceARN = nil
		}
		if elem.RevisionId != nil {
			ko.Status.RevisionID = elem.RevisionId
		} else {
			ko.Status.RevisionID = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return (r.ko.Spec.PolicyName == nil && r.ko.Spec.ResourceARN == nil)

}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeResourcePoliciesInput, error) {
	res := &svcsdk.DescribeResourcePoliciesInput{}

	if r.ko.Spec.ResourceARN != nil {
		res.ResourceArn = r.ko.Spec.ResourceARN
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.PutResourcePolicyOutput
	_ = resp
	resp, err = rm.sdkapi.PutResourcePolicy(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "PutResourcePolicy", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ResourcePolicy.LastUpdatedTime != nil {
		ko.Status.LastUpdatedTime = resp.ResourcePolicy.LastUpdatedTime
	} else {
		ko.Status.LastUpdatedTime = nil
	}
	if resp.ResourcePolicy.PolicyDocument != nil {
		ko.Spec.PolicyDocument = resp.ResourcePolicy.PolicyDocument
	} else {
		ko.Spec.PolicyDocument = nil
	}
	if resp.ResourcePolicy.PolicyName != nil {
		ko.Spec.PolicyName = resp.ResourcePolicy.PolicyName
	} else {
		ko.Spec.PolicyName = nil
	}
	if resp.ResourcePolicy.PolicyScope != "" {
		ko.Status.PolicyScope = aws.String(string(resp.ResourcePolicy.PolicyScope))
	} else {
		ko.Status.PolicyScope = nil
	}
	if resp.ResourcePolicy.ResourceArn != nil {
		ko.Spec.ResourceARN = resp.ResourcePolicy.ResourceArn
	} else {
		ko.Spec.ResourceARN = nil
	}
	if resp.ResourcePolicy.RevisionId != nil {
		ko.Status.RevisionID = resp.ResourcePolicy.RevisionId
	} else {
		ko.Status.RevisionID = nil
	}

	rm.setStatusDefaults(ko)
	// PutResourcePolicy returns the revision ID of the created policy at the top
	// level of the response, and only for resource-scoped policies. The nested
	// ResourcePolicy shape does not carry it on writes, so the generated mapping
	// above nulls Status.RevisionID. Prefer the top-level value so the status
	// reflects the revision immediately after create without waiting for a
	// subsequent read.
	if resp.RevisionId != nil {
		ko.Status.RevisionID = resp.RevisionId
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.PutResourcePolicyInput, error) {
	res := &svcsdk.PutResourcePolicyInput{}

	if r.ko.Spec.PolicyDocument != nil {
		res.PolicyDocument = r.ko.Spec.PolicyDocument
	}
	if r.ko.Spec.PolicyName != nil {
		res.PolicyName = r.ko.Spec.PolicyName
	}
	if r.ko.Spec.ResourceARN != nil {
		res.ResourceArn = r.ko.Spec.ResourceARN
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}
	// ExpectedRevisionId guards against concurrent modification and is only
	// valid for resource-scoped policies (those with a ResourceArn). Account
	// scoped policies do not carry a revision ID, so leave the field unset.
	if desired.ko.Spec.ResourceARN != nil && latest.ko.Status.RevisionID != nil {
		input.ExpectedRevisionId = latest.ko.Status.RevisionID
	}

	var resp *svcsdk.PutResourcePolicyOutput
	_ = resp
	resp, err = rm.sdkapi.PutResourcePolicy(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "PutResourcePolicy", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ResourcePolicy.LastUpdatedTime != nil {
		ko.Status.LastUpdatedTime = resp.ResourcePolicy.LastUpdatedTime
	} else {
		ko.Status.LastUpdatedTime = nil
	}
	if resp.ResourcePolicy.PolicyDocument != nil {
		ko.Spec.PolicyDocument = resp.ResourcePolicy.PolicyDocument
	} else {
		ko.Spec.PolicyDocument = nil
	}
	if resp.ResourcePolicy.PolicyName != nil {
		ko.Spec.PolicyName = resp.ResourcePolicy.PolicyName
	} else {
		ko.Spec.PolicyName = nil
	}
	if resp.ResourcePolicy.PolicyScope != "" {
		ko.Status.PolicyScope = aws.String(string(resp.ResourcePolicy.PolicyScope))
	} else {
		ko.Status.PolicyScope = nil
	}
	if resp.ResourcePolicy.ResourceArn != nil {
		ko.Spec.ResourceARN = resp.ResourcePolicy.ResourceArn
	} else {
		ko.Spec.ResourceARN = nil
	}
	if resp.ResourcePolicy.RevisionId != nil {
		ko.Status.RevisionID = resp.ResourcePolicy.RevisionId
	} else {
		ko.Status.RevisionID = nil
	}

	rm.setStatusDefaults(ko)
	// PutResourcePolicy returns the revision ID of the updated policy at the top
	// level of the response, and only for resource-scoped policies. The nested
	// ResourcePolicy shape does not carry it on writes, so the generated mapping
	// above nulls Status.RevisionID. Prefer the top-level value so the status
	// reflects the new revision after an update and the delete guard has the
	// current ExpectedRevisionId.
	if resp.RevisionId != nil {
		ko.Status.RevisionID = resp.RevisionId
	}

	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.PutResourcePolicyInput, error) {
	res := &svcsdk.PutResourcePolicyInput{}

	if r.ko.Spec.PolicyDocument != nil {
		res.PolicyDocument = r.ko.Spec.PolicyDocument
	}
	if r.ko.Spec.PolicyName != nil {
		res.PolicyName = r.ko.Spec.PolicyName
	}
	if r.ko.Spec.ResourceARN != nil {
		res.ResourceArn = r.ko.Spec.ResourceARN
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	// ExpectedRevisionId is required when deleting a resource-scoped policy to
	// guard against concurrent modification. Account-scoped policies do not
	// carry a revision ID, so leave the field unset for them.
	if r.ko.Spec.ResourceARN != nil && r.ko.Status.RevisionID != nil {
		input.ExpectedRevisionId = r.ko.Status.RevisionID
	}

	var resp *svcsdk.DeleteResourcePolicyOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteResourcePolicy(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteResourcePolicy", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteResourcePolicyInput, error) {
	res := &svcsdk.DeleteResourcePolicyInput{}

	if r.ko.Spec.PolicyName != nil {
		res.PolicyName = r.ko.Spec.PolicyName
	}
	if r.ko.Spec.ResourceARN != nil {
		res.ResourceArn = r.ko.Spec.ResourceARN
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.ResourcePolicy,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterException":
		return true
	default:
		return false
	}
}
