// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ResourcePolicySpec defines the desired state of ResourcePolicy.
//
// A policy enabling one or more entities to put logs to a log group in this
// account.
type ResourcePolicySpec struct {

	// Details of the new policy, including the identity of the principal that is
	// enabled to put logs to this account. This is formatted as a JSON string.
	// This parameter is required.
	//
	// The following example creates a resource policy enabling the Route 53 service
	// to put DNS query logs in to the specified log group. Replace "logArn" with
	// the ARN of your CloudWatch Logs resource, such as a log group or log stream.
	//
	// CloudWatch Logs also supports aws:SourceArn (https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-sourcearn)
	// and aws:SourceAccount (https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-sourceaccount)
	// condition context keys.
	//
	// In the example resource policy, you would replace the value of SourceArn
	// with the resource making the call from Route 53 to CloudWatch Logs. You would
	// also replace the value of SourceAccount with the Amazon Web Services account
	// ID making that call.
	//
	// { "Version": "2012-10-17", "Statement": [ { "Sid": "Route53LogsToCloudWatchLogs",
	// "Effect": "Allow", "Principal": { "Service": [ "route53.amazonaws.com" ]
	// }, "Action": "logs:PutLogEvents", "Resource": "logArn", "Condition": { "ArnLike":
	// { "aws:SourceArn": "myRoute53ResourceArn" }, "StringEquals": { "aws:SourceAccount":
	// "myAwsAccountId" } } } ] }
	PolicyDocument *string `json:"policyDocument,omitempty"`
	// Name of the new policy. This parameter is required.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	PolicyName *string `json:"policyName,omitempty"`
	// The ARN of the CloudWatch Logs resource to which the resource policy needs
	// to be added or attached. Currently only supports LogGroup ARN.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	ResourceARN *string `json:"resourceARN,omitempty"`
}

// ResourcePolicyStatus defines the observed state of ResourcePolicy
type ResourcePolicyStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// Timestamp showing when this policy was last updated, expressed as the number
	// of milliseconds after Jan 1, 1970 00:00:00 UTC.
	// +kubebuilder:validation:Optional
	LastUpdatedTime *int64 `json:"lastUpdatedTime,omitempty"`
	// Specifies scope of the resource policy. Valid values are ACCOUNT or RESOURCE.
	// +kubebuilder:validation:Optional
	PolicyScope *string `json:"policyScope,omitempty"`
	// The revision ID of the resource policy. Only populated for resource-scoped
	// policies.
	// +kubebuilder:validation:Optional
	RevisionID *string `json:"revisionID,omitempty"`
}

// ResourcePolicy is the Schema for the ResourcePolicies API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type ResourcePolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ResourcePolicySpec   `json:"spec,omitempty"`
	Status            ResourcePolicyStatus `json:"status,omitempty"`
}

// ResourcePolicyList contains a list of ResourcePolicy
// +kubebuilder:object:root=true
type ResourcePolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ResourcePolicy `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ResourcePolicy{}, &ResourcePolicyList{})
}
